image: barichello/sfml:latest

variables:
  GAME_NAME: multicaster

stages:
  - build

linux:
  stage: build
  script:
    # Build
    - scons -j 4
    # Package
    - mkdir bin/lib
    - cp /usr/lib/x86_64-linux-gnu/libsfml-*.so.* bin/lib
    - mv bin $GAME_NAME
  artifacts:
    name: $GAME_NAME-linux64
    paths:
      - $GAME_NAME
  except:
    - wip@gitlab-org/gitlab-ce

windows:
  stage: build
  script:
    # Pre-build: dependencies
    - mkdir include && mkdir lib
    - cp -r /SFML-2.5.1/include .
    - cp -r /SFML-2.5.1/lib .
    # Build
    - scons --cross=1 -j 4
    # Package
    - cp /SFML-2.5.1/bin/*.dll bin/
    - mv bin $GAME_NAME
  artifacts:
    name: $GAME_NAME-windows64
    paths:
      - $GAME_NAME
  except:
    - wip@gitlab-org/gitlab-ce
