image: barichello/sfml:latest

variables:
  GAME_NAME: multicaster

stages:
  - build

linux:
  stage: build
  script:
    - bash build.sh linux
  artifacts:
    name: $GAME_NAME-linux64
    paths:
      - $GAME_NAME

windows:
  stage: build
  script:
    - bash build.sh windows
  artifacts:
    name: $GAME_NAME-windows64
    paths:
      - $GAME_NAME
