image: barichello/sfml:latest

variables:
  GAME_NAME: multicaster

stages:
  - build

linux:
  stage: build
  script:
    # Build
    - mkdir include
    - cp -r /lua/include .
    - cp /sol.hpp ./include/
    - scons -j 4
    # Package
    - mkdir bin/lib
    - cp /usr/lib/x86_64-linux-gnu/libsfml-*.so.* bin/lib
    - mv bin $GAME_NAME
  artifacts:
    name: $GAME_NAME-linux64
    paths:
      - $GAME_NAME

windows:
  stage: build
  script:
    # Pre-build: dependencies
    - mkdir include && mkdir lib
    - cp -r /SFML-2.5.1/include .
    - cp -r /SFML-2.5.1/lib .
    - cp -r /TGUI-0.8/include .
    - cp -r /TGUI-0.8/lib .
    - cp /sol.hpp ./include/
    - cp -r /lua/include .
    - cp -r /lua/*.a ./lib
    # Build
    - scons --cross=1 -j 4
    # Package
    - cp /SFML-2.5.1/bin/openal32.dll bin/
    - cp /SFML-2.5.1/bin/sfml-*-2.dll bin/
    - cp /TGUI-0.8/bin/tgui.dll bin/
    - cp /lua/*.dll bin/
    - mv bin $GAME_NAME
  artifacts:
    name: $GAME_NAME-windows64
    paths:
      - $GAME_NAME
